spring.application.name=user-ms

server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/users}
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

broker.queue.eatery.name=order.created
broker.queue.user.name=code.created
broker.queue.code.validated.name=code.validated